### ISSUE TITLE
amdgpu support

### ISSUE THREAD

**Issue by leissa** [AnyDSL/runtime#2]

**Comment by richardmembarth** [comment]
We have now a working amdgpu implementation.

Thorin: [amdgpu branch](https://github.com/AnyDSL/thorin/tree/amdgpu)
Runtime: [HSA branch](https://github.com/AnyDSL/runtime/tree/HSA)
Stincilla: [amdgpu branch](https://github.com/AnyDSL/Stincilla/tree/amdgpu)

The code generation is based on the LLVM AMDGPU back end and uses the HSA runtime.
Math functions are linked from [OCML](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/master/doc/OCML.md). Tested on a system running [ROCm 1.5](https://rocm.github.io/install.html).

**Comment by richardmembarth** [comment]
Merged.
