### ISSUE TITLE
OpenCl unsupported pointer

### ISSUE THREAD

**Issue by r-verr** [AnyDSL/runtime#3]
../anydsl/thorin/src/thorin/be/llvm/runtime.cpp: 116: argument alloc_11243 of aggregate type Buffer at ../anydsl/runtime/src/runtime.impala:56 col 48 - 82' contains pointer (not supported in OpenCL 1.2)

**Comment by richardmembarth** [comment]
What's the problem here?

**Comment by madmann91** [comment]
It's a warning, unless you actually use the OpenCL backend. It should not prevent you from using the CUDA or NVVM backend. This is not a bug, but a limitation of OpenCL 1.2.

**Comment by madmann91** [comment]
Here is a possible fix if you **really** want to get a rid of the message. You code should look like this:

```rust
let buffer = acc.alloc(...);
with acc.exec(dev, grid, block) {
    // ...
    buffer.data(...)
    // ...
}
```

The compiler has to pass `buffer` as an argument to your kernel. You can pass the pointer directly instead of the buffer, and the warning should no longer be triggered:

```rust
let buffer = acc.alloc(...);
let data = buffer.data;
with acc.exec(dev, grid, block) {
    // ...
    data(...)
    // ...
}
```
